version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: ENC[AES256_GCM,data:m+Jhjn3FzRWRW5dDjJToIkah7JAs7h0=,iv:TrFkXY41WuLQIA0xGc2gPxOaBDvIxNsR9u3zXSK9DP0=,tag:7FhRphqk6Lie9Ev8OnRU6w==,type:str]
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBdWh6OW5IRHFOanFjQTNDRkhoRkZrakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXdPREkwTVRVek56TTJXaGNOTXpVd09ESXlNVFV6TnpNMldqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUJXWk52ekUzK2RLanJKYjA2UzV0N0JUdXd6TFlGVUNGZHNjCjlRdzduM3IzbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkRaTncyb2IvK0NQbzJSTQp6My9hWVEwK0VBR21NQVVHQXl0bGNBTkJBREtSTzBRYlByUDFscGdleHFodFk0d09ZUFpiaVJoVjEzeXJYQUc5CmUxeE00N212M1VCeStvcWRSL0diQ044RmdoS1VpNUJhMExCVExLYitacGF6MUFrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: minipc1
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.10.1
        wipe: false
    registries: {}
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    kernel:
        modules:
            - name: uio_pci_generic
            - name: vfio_pci
            - name: nvme_tcp
cluster:
    id: 4LIl1i1ULF2cBcU57RDbqrSkyxXQu5k_S29ffunxilY=
    secret: ENC[AES256_GCM,data:3iRabINSB50AIhs8wMtA6SYuXFUiFDfKh96+ZUQKiMK2ZDewhZ8lf3i38zs=,iv:itkqeNjUE3kC+SvYNoScVVLWFCabquFZyxEwsa+/Teg=,tag:dV13YlltPuPiPQKJ0IjBZQ==,type:str]
    controlPlane:
        endpoint: https://192.168.20.115:6443
    clusterName: understairs
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: ENC[AES256_GCM,data:3IAp6t7E7eGHO6zpYL3JqrY+RX8gSYI=,iv:qjMDgnAZeb+7Ea5Cj2v3K6kDBQO6dleQhLkkw/bPuOs=,tag:So8DMOsnNC66BI3/bEFOeg==,type:str]
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRWUN3SzJWTjVON3pHSHZFbzJMdGJFakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGd5TkRFMU16Y3pObG9YRFRNMU1EZ3lNakUxTXpjegpObG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQ3N0b2R3Ykw2ZEl5eFRaVWJnMnIrSEx0SFMrV3JDK0wweEVsM2ZUUEkwekZXcjhDMm9QSnJTdXRTdzcKaWNYSXFmODB2aW85Nm5OQXdEUEI3MnBEaE1XallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVPVmJ5RWFSWDNEdk9QSS80Q2FoSnAwNkhadEl3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSHRMOFB5OW4KVzBBSkNXcGg0N21MakRkSmpoR3FoRTVNaHNQM0JRNGxwRzRDSUV2RXNsWExldEVvdlJxVVo3ZEF3RHBXcVJ1eQo3VGc5WnE3TWw0TTJvMzhXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: false
            service:
                disabled: false
sops:
    age:
        - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRENtVG8xQWhGa3czSkhr
            clpxNEIxemZPTGJJVFM5UEp1bUxXeEpCVWpRCkhVZ1B3R2tqMFBGa2JOT1hpd2tI
            Z1VyQUV1RFNWNitmZ1M4WGcxSEZROFUKLS0tIGtnK0VFQ0FTNG14WDRyTmlkMS9P
            WWE1dkVqVS9XYmM3cUU1Q0g1ZHNhQlUKhbrGTEyAX5ihfsfiWnF0c2tCT6D7PBh2
            MVEf/0y0u2/8YipA68cZ8MCLyzMYyARUQo3X54RJKlMMvVpMqxlOHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T08:49:25Z"
    mac: ENC[AES256_GCM,data:sZyq4QTpeN2Q+9hK1+/apHxCi/MU6myD0y2rbwuBuaFd+PsznzsO0JaI7JleAkPBAQA0m/J0zjFTZRXloN/syMJ5JI4JmAsxSt5z4at5ZADRSWrOBB1wPFDzDJkWpkrlpUPKyWX8ukC3Px2LwfCTPRLWhjG0pJBAF9oBRA8CCGg=,iv:FWzyWE2P6UltaF5Ot5dszk1NRwl2jfFwdY73RizokwM=,tag:yxeeUJsTBxvjV82a7I7nHA==,type:str]
    pgp:
        - created_at: "2025-12-24T15:12:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ/9FtnwMVWNbQB7ASfK+xSIp3VoLzeIP02i7MvtcpuLvB+s
            mDJ3+VloHj1+50wsoe0k1rKjymFs72d/zMUsPaO9P6D+8ljVIt67bX9+IlqV7b1y
            PokuH3BuMeAuYa0WtzjNSMgjK2ocGJSBkqNfYYzryP+sDsTVQiSNlL5upcDtuGhS
            iWoBQIp3+4V1NFX8XKSfUB+QiqlBlZYaQ5u+Mpugh5dR3VgTOTKd9DVSl9eyPDaZ
            y7k1HvsyydYouphBy0iypvdBRg3fPo64K0T4Xlx1zpycPJuCDu2yoGlNXFle8aUW
            qoAPJfeQK56DFYMS+yWvqwnMDixiMLNmBAs+bt6JqOgDBOTAP6mQv8BcaaeOiCPr
            Xw3YG59hGPH2GOExdsT+YBz6U2tx8CJGzb+dZf1w36s/JRcg4vS2lE6fhdG8Lg1X
            QziViGzr8n6DJmlu5I3BoEoy7KLbIo2ssLpBgjmGDOcB7M9bwXh/qGnX+0VPs2u3
            11svsdUyyjLPoC+8iJbDXU900JzYwqTXyAhtgTvwDkfs1uLCkbi2tq7aDIFxBfjn
            nIGlT9KYKpANsU0Ib+Jy1DpbmBOcF4e3waY6Aja0X+YLNxmauGche9Uq9nFeW8/b
            Q1FulhC5/QoYbob3h88KIo5G26zCpgaxBsSEyvGy0cO0LsRnFIkYAeS+QTIcOj3S
            XAFA9Rc4LWvyC5Kun3Gxl4HXfOx6l9xYF/zSAazPvcTOs5cMTUvoWjAB6PCmFRBi
            JzJg5doiUdfAK3YHU8PWGeRdKttYaqsfMj06VN7cHDphBRiCbLKPPK439dW7
            =zpSj
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
        - created_at: "2025-12-24T15:12:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ//TdKMuNjwblkQBdollT9Tf1lIor2S5yy9VbT0BMJ2u/4O
            PY9HS9ZrSeh24ogD/n7baQf8tMCm4Svo9PeNxH2f+chbxQPjPUAPb6c+YOtd2yRp
            u2Xgvjhr9BxkcYGG2+vYKwFPhGRK1xgm9GjXvQgwaKNUa4WfewJgXfpik2jluLGh
            1vEjtKRANdU/hoBDJJmdIl4RgNtrrhSvAyEiCaFCDKLqJPmUQ4FCYlMV4h9/6fba
            NkRhFArIUiAZ0z6DZ3bTqd3IY5ddT/QgGByMQUwtR9qpAHGebsXdSIat1UXZ/a4R
            2rGs7G152vCvtwBW/quJGHTm2Rtx5gqYfbIEyurqMFBs+fe9YsgcgcI5zSdrg60K
            JDgFp/QKd6yOw+fOm86p1KoHXF9wltYo+oowkwf+rfb9gGzoSZk6rrI9xl5l7ZoH
            sUCixQ/AFW/NC62x1Tj9AqO8X1mjNopHEyLWbNUErL//724l8/d5PxeSt5RdKkFp
            Y1YNaKWdNYWOBEnYkV8sszVFxmvAP8wUhWzNtqS+CBebHQX5YYPWu4/ozBMeZXi6
            Rf1xk0qibezhp91rOLbkeMP97hjfia+iuaZeIcLNZwgc8CWBR/gktxM0c02UvFGW
            Og/IolBN/uKKurzHVWx0v5PW79XT/ODNW1zQH+a0n1sgZrzZUX76g3XFNB4jCQ7S
            XAEp/WN4LTIsKqgjlfrnTZ5X3DrOXzWVn8shNVe6s9DGxH6D42so5VnQ+BNeH/Yf
            6v8gt6Cnws2/c1r7SEIHNechKLrGU72pZFW5dy/bc5k6DPdIEWDlAmKABmdC
            =V4w0
            -----END PGP MESSAGE-----
          fp: 67E1798C7B7A5D23
    encrypted_regex: ^(token|secret|key|secretboxEncryptionSecret)$
    version: 3.11.0
