username: ENC[AES256_GCM,data:1+oG6z/cng==,iv:4oihi1+XuoXunROIQhaaCzswYV2wrbu68nJYH/s4ULs=,tag:tpST9JjlSxe+ti+g2drMNQ==,type:str]
password: ENC[AES256_GCM,data:maZzpDiqHRd8owfi,iv:9d6LiW2BTThLngOjv9vcWCVbmgS60zAQxLajgTdGWx0=,tag:RWGSI35/Ii4p5rMG9BiVWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1afmdvukptgq0g69hmvkj8pc5juda2v753tfyxnsmcj22q03je5rqz7mt52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbVdybjM2SmVXdXNTdXda
            ZVFQOW5DNkRiT3FtY0c4eHVwUUQ0S0haeDFrClU4VTBuRVQ3Q0xVdGhsNDBkczRk
            S3E2UXVPc3RkMnVhN0UwOEo5cmRlUVEKLS0tIE4rSW9oZWdNL3VoK3JyaWF3NzEy
            ZllPUVR0amxwSHA1YVpZK3lsZi9tdEEKauKbzVKbwrD85MtGZX1FJ0YClnJpA4VD
            bpYcA0uM94SosET8+AAAYFtm5qQtVxm61CpH/tVLsUIjXqKOIy1+cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:21:54Z"
    mac: ENC[AES256_GCM,data:PLHuKc0uJlJdd3ch3oZNC21VzNAdVtaEeTvs1JTyKYm7z2IP4xKLFr4H2U8cCvr7Evi88GL3VyTysTR8J4MZ2LeGLxR/D0KTyl+MBEgpSOHHGUcnGdx6r2+o6mnDU6UfqzJ+OZwsmkQ4ee5F9r2+eVIIOz9PoJ4Q5XkD+Z9dZSQ=,iv:yn5iNx0bMVdqvzg3egoVFZv2YAXZU+26KDV9lL2st3c=,tag:nWXQLdMmrqJFgX+HGAHCTA==,type:str]
    pgp:
        - created_at: "2025-11-01T17:11:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ/8CRDX/q7c7Yf/gyd+1GTVnrT/RiaOefIOXUKXkZHK9wKH
            2S9FD51/e36kbHhfiy+0rXJiyBDQR54pb0BUWxUnYONydWRSfBz2uBzzLKGyNkSU
            nJ6bQXMfDLPODTWdMDCgtjcGkuPttwSYXn3Xy0gn6qdiCXXOZI+d9vik4ULCKS6v
            9BAhbSCrV+QJ95oTkF2qA1M9OyGADHOkecPcSi9m/XxSQ8BEm8OPTjlAT9XOzWhN
            //JBsVRNqsntvyHa4ENtdLn+vsFzVD9wYL40aBhBoew+RuKbPfY+M8nlOXTu3ILu
            6BFdxjY6VMXEHVQO5rw2buIaaXkz7NvB1QejpGobqFDpIJ6+TL9dWTTYiwPtyiUV
            FalHbK9gynBwhEHKVBgMoiWns1Rlskj7A7BxxIM5K+KK/e+6OirXwLgrHlyd5dpC
            +/celmXe6JXevVcs2oAXb2csd+g34WBy4zANrRxfJr3Tp0nxtW8iADIkYlZl8NaH
            L8PZ7s5PZgBEmPQMMZgmzZ5wK5nUuLYv0YNfo1RThT1oGy8JPiiyo2RkI9W2dv1+
            vJT5K472+3o8RegMtf3K2rA/Vp18ng+DqYDnimluMifwNz888FnLjGhNKtcbQ6RE
            XwUBqZM6ntW4ubIJy0rOTOOPZWn841gCDWF8OMx32/C5Jm1JfWPHuDWW9TnLB2vS
            XAFtW9koR7vS1biHqAA0s87f9wOzPUAPMhaejON8RczlbPkoxDq5Fq49mKHK8Jvb
            b2df76s4z1i6sBl0mIJfMzirVRL9E3pMv0x6A/9BawPjJ3L72DE+YLF00lVr
            =AS3b
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    unencrypted_suffix: _unencrypted
    version: 3.9.3
