username: ENC[AES256_GCM,data:1+oG6z/cng==,iv:4oihi1+XuoXunROIQhaaCzswYV2wrbu68nJYH/s4ULs=,tag:tpST9JjlSxe+ti+g2drMNQ==,type:str]
password: ENC[AES256_GCM,data:maZzpDiqHRd8owfi,iv:9d6LiW2BTThLngOjv9vcWCVbmgS60zAQxLajgTdGWx0=,tag:RWGSI35/Ii4p5rMG9BiVWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-01T16:21:54Z"
    mac: ENC[AES256_GCM,data:PLHuKc0uJlJdd3ch3oZNC21VzNAdVtaEeTvs1JTyKYm7z2IP4xKLFr4H2U8cCvr7Evi88GL3VyTysTR8J4MZ2LeGLxR/D0KTyl+MBEgpSOHHGUcnGdx6r2+o6mnDU6UfqzJ+OZwsmkQ4ee5F9r2+eVIIOz9PoJ4Q5XkD+Z9dZSQ=,iv:yn5iNx0bMVdqvzg3egoVFZv2YAXZU+26KDV9lL2st3c=,tag:nWXQLdMmrqJFgX+HGAHCTA==,type:str]
    pgp:
        - created_at: "2025-10-31T17:16:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ/8Cy7rg2xZmwNHZ3AwGmnaFpREIPPpL7BGCE/voN109vf6
            ayHzUDSGgp968sCsnIFt9fR4H2y1i+wJX8tDq8EZOiMLfcM50GUDVqlBA2NhE4FL
            N0VtEHnCDRa2QAW0oZZeFzcw2hx9nnAyavB/bBXJN144upYB2GCEZzNXZPdnRZXN
            acvhaV+ECHFFlIimxSDjsdYOflCMbEb9kqvwRa76E+hDA/ETYaOUlcPMS2Pjc6O+
            sE3kxstIFpkNAWystWiFEGcBsOb8soO+07WuP4Wk/py63szGmtlfJt0HG3l1WUDw
            t4zidqVHaMXww92sso0GFNqrCf3uRHgE28DCxEZ6XdSgKHCNwEalhKzaFxQ4xL2Y
            hvSiRhTi/s7k1Lcdn3FrdeVlcz2usuwsl+jI/Fq/HUHWzRzgUtyAtTLqQK3bkzQo
            c4a/aExRCJycw963GSlx6rCaCZwmEc11AQ9SWJ0cdgpbFwcOQjgaYOU4OwRts4wD
            c14ZgBtagzVdg1YprZRxS0bmjX17IHxGBzuvCjkgBo4ntg2HoljabYkQ1fPGTcDg
            Lgq3u8yNBJTKvo3N249vQWnvB/6PTwspCi4HRCOD6t9sTgJQlfRiNJqyaIBRueTi
            lGZLBLuDJjkNntgY8WeHBL919mskTDUz2TlwWHexdnRg5D5dLfJJ5dpwZGxTshfS
            XgGIOsJrovHrWGR1Wn7QKgTBUgs9mFBphBIcSd5aheeka/66u4zCXbflT8AqyGg3
            9wjmxgmMyKrSHnqShoKpICxzD7sMLv/LAzeWMZSAER909l5eg6gkTPpGmo06nzE=
            =LWO2
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    unencrypted_suffix: _unencrypted
    version: 3.9.3
