username: ENC[AES256_GCM,data:nUIuTJ+vFelbM63W,iv:zzqNiSKCPpdWSNLTrOG6FTQ5YWCT2WGghXb2XSVjfrQ=,tag:pJSnqlF+864FwBucThWLEg==,type:str]
password: ENC[AES256_GCM,data:Ks2t7Ke5k8o=,iv:FlAGPXNwkzC2NL5cqjzv5orrYTncCfvREsg/9ZkM+wQ=,tag:H/zmuetM6h+q3eoJ8wfdaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-01T16:21:43Z"
    mac: ENC[AES256_GCM,data:exaNfQFz4980hm399w7LOntbgJOc2RB3BWYGYYhPNqdnvfHrBaLysWixBVPZlTZyTFb59mm9g88Kf6F1LcYwNZKOuSsU97v0AJnH0aHU7koUROSkl7m31xX/UQ2FpWYHl5j5eqU0+suDR78qTjG9CsbhqvF/hs9slWwheS6o8cc=,iv:ZASpV1ME8fXOrbNSguDN64sivQpE/vNm9S7Ip0+JqRk=,tag:Kq2027IK5HwFoefnAU+CtQ==,type:str]
    pgp:
        - created_at: "2025-11-01T16:18:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jAQ/7BRYEvTr1wrUb/Nfs8EO6bcOSY3wDWf/89eyuXipYSlGb
            KeGyFTybQqXFXIVZHXJNtM5CBkGr71bQqMuzU/4tQj4/qxJT3FlXmDhOXMjXNit9
            dinLeHr8WI2GoYc6VluMptuzUSKM4Ez2vyIRQ7M3mTQ9AX1jKD6xaqHOMdtgdbfQ
            /SU3ZboWAVg0CDmnQ8IHjwtZFcd7vsZs/kV5nj5mgPmOmAS5mF/uEmlIDydVKVqV
            N9ca+lIVztkQoCwBcqgGPSRqblw0nVIsYltZ2xnMd69Wbv6rFARnQvwCCPKliq34
            9KtJP0I2R540ZXnlCVvQFvQEDSjIVPkBCJv1/paYW0z7UDmTKXAi+gHwslJpoekq
            MMz7SZk4I8I54cQA0ZowtmgWLAvW3eIQPy+cPQRLvAROobxhH722vp/ezr+hjeEv
            6SabECfHw5b4IohdjvQq+gCqHzdob1sg+cnVvJ065sel4ROE+VRZn+LzhhqtpWOP
            hiNKamhovtDHcDC7/h8j+qQUSxQKwebBwG+o1r33CDuN+j8aZbnBq9343rw1KaXQ
            I3XDRq7GDnil8pkr9hOJDDCEd6+as8F2KGKtVwL7sBqe1Twf4B/pDdcOxXFA3RIM
            kTfM5svtGNVIpaTBS2mbmIi1RXMVXZ0m9wS2/5rHaxaLXxWNUOfBIMiHz4qzTSbS
            XgFjbwuUdcY22pC2NsoAhUt8PhKukrHwKhAuT9pFokHxnbbz5Hjk85nRdTtn8EJP
            vMSDfV6+Ce2Y4ZHUb280Nt2Yhqr6xB/FdbiTyufIo7lhfQnkBrJ+mf1goNQ2UZQ=
            =32Wc
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    unencrypted_suffix: _unencrypted
    version: 3.9.3
