username: ENC[AES256_GCM,data:nUIuTJ+vFelbM63W,iv:zzqNiSKCPpdWSNLTrOG6FTQ5YWCT2WGghXb2XSVjfrQ=,tag:pJSnqlF+864FwBucThWLEg==,type:str]
password: ENC[AES256_GCM,data:Ks2t7Ke5k8o=,iv:FlAGPXNwkzC2NL5cqjzv5orrYTncCfvREsg/9ZkM+wQ=,tag:H/zmuetM6h+q3eoJ8wfdaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1afmdvukptgq0g69hmvkj8pc5juda2v753tfyxnsmcj22q03je5rqz7mt52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMEZ4d0dyMmw5RG52SlNW
            aXBJUisvVDhMZ25qaWpmRFdXemlLUHZ4M0JNCkZzWnVQMklHUVpsdDRCbGhlN2lu
            cU9RKzlpTElBenkycEptOVF2YzY3c3MKLS0tIHBZNWxsUXRiMVA0ckNyRVV4aG9J
            SGRhZ3ZrSlNPb24wQ3J1QWFMUFMvZ1kKNWfKWuiGNZmGoCFqgXq1WoYwj++x2xtA
            l6KLFlIv78jzg/4yLVZ9uxSRngDbdC9h5/vMYtuR41othi/OK3eNIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:21:43Z"
    mac: ENC[AES256_GCM,data:exaNfQFz4980hm399w7LOntbgJOc2RB3BWYGYYhPNqdnvfHrBaLysWixBVPZlTZyTFb59mm9g88Kf6F1LcYwNZKOuSsU97v0AJnH0aHU7koUROSkl7m31xX/UQ2FpWYHl5j5eqU0+suDR78qTjG9CsbhqvF/hs9slWwheS6o8cc=,iv:ZASpV1ME8fXOrbNSguDN64sivQpE/vNm9S7Ip0+JqRk=,tag:Kq2027IK5HwFoefnAU+CtQ==,type:str]
    pgp:
        - created_at: "2025-11-01T17:11:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jARAAp7aNit1C0cjQBQAUpdctlCaYu+Wr9SV1GXQdIsNwcYHD
            QarsbPKuLmWO4oeVpGDtOCaBtkbIoZFvH6JiLuYSGwTzjWdczRIUUVHPPEXK8yVy
            UnNMho7LMavqdHVCmKqM23gNOAO2JYInOzb8VSDkIusMt5kQ+VatqQQbODHBA1Dk
            B/LPnBZqDm8loGQIJU5noOEghpMMt3i5vFSwAtEKSTslQyZlGmqhi/3f//ebc+yY
            s5XciiAmFD8EcJxe4RzOYo0Fg4N148frRjk5x8TAqWhJrl99pkxmEMxFMzE9XEKo
            TNj3AWb0jWQmutzUyELiC/gf40iA6XAtuXnlj0Bd6M1OjtMmsFyNuvXfnlU5N8Iz
            mgozlcF73xyxU9Euj6HhhokS89WKV4ChZeP5q05423MsS3KwlSSPeuRO/penjgnW
            i2OiPXVbJ4PuY9wRCl+6834d3BGaq6bW7wjt1UKAYAL5+HspagLCBQxCbmSOwRxW
            zIcxwvRLnke5Tq1dFpscuJJG585K+17usSGVNVR6LAKb9U1Icre8J2FKXyokFgjU
            SoqQWm7FQaxVvk3SESzZV6xMF+ZJ+5Y81wViC0A8QBtS7k/+i7oVOZ0f0KMbEs+f
            f8Alpx6ZEXfX4aUgJl0jevGOrp0R7OM5JWKDU4dt1dK8CW8zq6LFFUzffyKEyuTS
            XgHziQ2P5PEzn3UL1YgPT7CMzsxC2BQodhyLUvS9SVN/Cu96IBerqjc3K0Hw7ywc
            Or0Ayf18CFMSAWeiyTdyCsHudxC25niNW1nq4+kOue0F+5D41kXfUblFBU0vLEA=
            =ZC04
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    unencrypted_suffix: _unencrypted
    version: 3.9.3
